use metastore;
DROP VIEW IF EXISTS view_tag_meta_col;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW view_tag_meta_col AS
SELECT
  DBS.NAME as DB,
  TBLS.TBL_NAME,
  COLUMNS_V2.COLUMN_NAME,
  COLUMNS_V2.TYPE_NAME,
  COLUMNS_V2.COMMENT,
  COLUMNS_V2.INTEGER_IDX,
  0 flag
FROM
 COLUMNS_V2 ,
 SDS,
 TBLS,
    DBS
WHERE
 COLUMNS_V2.CD_ID = SDS.CD_ID
AND SDS.SD_ID = TBLS.SD_ID
AND TBLS.DB_ID = DBS.DB_ID 
order by COLUMNS_V2.INTEGER_IDX;

DROP VIEW IF EXISTS view_tag_meta_partition;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW view_tag_meta_partition
AS
SELECT
  DBS.NAME as DB,
  TBLS.TBL_NAME,
  PARTITION_KEYS.PKEY_NAME as COLUMN_NAME,
  PARTITION_KEYS.PKEY_TYPE as TYPE_NAME,
  PARTITION_KEYS.PKEY_COMMENT as COMMENT,
  PARTITION_KEYS.INTEGER_IDX as INTEGER_IDX,
  1 flag

FROM
 SDS,
 TBLS,
    DBS,
	PARTITION_KEYS
WHERE
SDS.SD_ID = TBLS.SD_ID
AND TBLS.DB_ID = DBS.DB_ID
AND TBLS.TBL_ID = PARTITION_KEYS.TBL_ID  
order by PARTITION_KEYS.INTEGER_IDX;

DROP VIEW IF EXISTS view_tag_meta_all;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW view_tag_meta_all
AS
select * FROM view_tag_meta_col
union all
select * FROM view_tag_meta_partition;

DROP VIEW IF EXISTS view_tag_meta;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW view_tag_meta
AS
select DB,TBL_NAME,COLUMN_NAME,TYPE_NAME,COMMENT from view_tag_meta_all
order by flag,INTEGER_IDX;


-- select * from  view_tag_meta where TBL_NAME = 't_phone_activity';