spring:
  profiles:
    active: local
  datasource:
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 默认数据源
    default-datasource:
      url:  jdbc:postgresql://10.10.201.2:30001/transpaas
      username: postgres
      password: TestBGLech0^Wa
      driver-class-name: org.postgresql.Driver

    # 多数据源
    target-datasources:
      datasource1:
        url: jdbc:hive2://10.10.201.12:8686/transpass_tag;AuthMech=0;transportMode=binary
        username:
        password:
        driver-class-name: org.apache.hive.jdbc.HiveDriver
        max-pool-size: 2
        connection-timeout-minute: 10

      datasource2:
        url: jdbc:hive2://10.3.3.19:10006/basic
        username: hdfs
        password: hdfs
        driver-class-name: org.apache.hive.jdbc.HiveDriver

    # druid 默认配置
    druid:
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
---
spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        show_sql: true
  datasource:
    url:  jdbc:postgresql://10.10.201.2:5433/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
---
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:/mapper/*.xml


